
;; CharfixCallerELISP.el was generated by InvDash2.0 authored by David Harris
(load "/media/chuggboarder/CHUGG/home/RM06analyst/InvDash2.0/code/charfix.el")
(charfix-folder "/media/chuggboarder/CHUGG/home/RM06analyst/InvDash2.0/UnprocessedData/SAPspool_20250331"
"/media/chuggboarder/CHUGG/home/RM06analyst/InvDash2.0/ProcessedDB/SAPspool_20250331")

