-- dotOpener.sql was generated by InvDash2.0 authored by David Harris

-- the text writes will generate here
.cd "d:/home/RM06analyst/InvDash2.0/code"


--once we know where our files need to go we can prepare the charfix instruction.

.output CharfixCallerELISP.el
select
'
;; CharfixCallerELISP.el was generated by InvDash2.0 authored by David Harris
(load "d:/home/RM06analyst/InvDash2.0/code/charfix.el")
(charfix-folder "d:/home/RM06analyst/InvDash2.0/UnprocessedData/SAPspool_20250331"
"d:/home/RM06analyst/InvDash2.0/ProcessedDB/SAPspool_20250331")
';

-- once our CharfixCallerELISP.el is written we can perform the shell call for charfix
.shell d:/WinApps/Emacs/emacs-29.4/bin/emacs.exe --script d:/home/RM06analyst/InvDash2.0/code/CharfixCallerELISP.el

-- now that we have our files prepared with charfix, we can do a simple preliminary import
-- to check our files against our manifest and set up the main import.

.output SP02DotImportSQL.sql
select
'-- SP02DotImportSQL.sql was generated by InvDash2.0 authored by David Harris
.import "d:/home/RM06analyst/InvDash2.0/ProcessedDB/SAPspool_20250331/charfix-sp02.txt" SP02import
.import "d:/home/RM06analyst/InvDash2.0/ProcessedDB/SAPspool_20250331/charfix-manifest.txt" charfixmanifestimport
';




--Lets dump our parms as rendered SQL content so we can read them back in to the database
--we are about to open.
.output parmdump.sql
.dump

-- our SQL will operate on this database file from here on.
.open "d:/home/RM06analyst/InvDash2.0/ProcessedDB/wrangle.db"

-- remind the new session where we want our text writes
.cd "d:/home/RM06analyst/InvDash2.0/code"


