-- SP02DotImportSQL.sql was generated by InvDash2.0 authored by David Harris
.import "/media/chuggboarder/CHUGG/home/RM06analyst/InvDash2.0/ProcessedDB/SAPspool_20250331/charfix-sp02.txt" SP02import
.import "/media/chuggboarder/CHUGG/home/RM06analyst/InvDash2.0/ProcessedDB/SAPspool_20250331/charfix-manifest.txt" charfixmanifestimport

